twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        mailer_contact: '%env(MAILER_CONTACT)%'
        app_team_name_1: '%env(APP_TEAM_NAME_1)%'
        app_team_name_2: '%env(APP_TEAM_NAME_2)%'

when@test:
    twig:
        strict_variables: true
